apiVersion: gitlab.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  credentials:
    source: Secret
    secretRef:
      name: gitlab-credentials
      namespace: crossplane-system
      key: credentials
